from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image


WORLD_WIDTH = 1440
WORLD_HEIGHT = 540
KEY_COLOR = (255, 0, 255)
TRANSPARENT_DISTANCE = 64
OPAQUE_DISTANCE = 144
COLLISION_ALPHA_THRESHOLD = 128


def chroma_alpha(pixel: tuple[int, int, int]) -> int:
    distance = max(abs(pixel[0] - KEY_COLOR[0]), abs(pixel[1] - KEY_COLOR[1]), abs(pixel[2] - KEY_COLOR[2]))
    if distance <= TRANSPARENT_DISTANCE:
        return 0
    if distance >= OPAQUE_DISTANCE:
        return 255
    return round((distance - TRANSPARENT_DISTANCE) * 255 / (OPAQUE_DISTANCE - TRANSPARENT_DISTANCE))


def remove_chroma(source: Image.Image) -> Image.Image:
    rgb = source.convert("RGB").resize((WORLD_WIDTH, WORLD_HEIGHT), Image.Resampling.LANCZOS)
    output = Image.new("RGBA", rgb.size)
    result: list[tuple[int, int, int, int]] = []

    for red, green, blue in rgb.getdata():
        alpha = chroma_alpha((red, green, blue))
        if alpha == 0:
            result.append((0, 0, 0, 0))
            continue
        if alpha == 255:
            result.append((red, green, blue, 255))
            continue

        key_distance = max(abs(red - KEY_COLOR[0]), abs(green - KEY_COLOR[1]), abs(blue - KEY_COLOR[2]))
        coverage = max(0.25, min(1, key_distance / 255))
        foreground_red = round((red - (1 - coverage) * KEY_COLOR[0]) / coverage)
        foreground_green = round((green - (1 - coverage) * KEY_COLOR[1]) / coverage)
        foreground_blue = round((blue - (1 - coverage) * KEY_COLOR[2]) / coverage)
        result.append(
            (
                max(0, min(255, foreground_red)),
                max(0, min(255, foreground_green)),
                max(0, min(255, foreground_blue)),
                alpha,
            )
        )

    output.putdata(result)
    return output


def build_mask(image: Image.Image) -> tuple[Image.Image, list[list[int]]]:
    alpha = image.getchannel("A")
    pixels = alpha.load()
    mask = Image.new("L", image.size, 0)
    mask_pixels = mask.load()
    columns: list[list[int]] = []

    for x in range(WORLD_WIDTH):
        spans: list[int] = []
        start: int | None = None
        for y in range(WORLD_HEIGHT):
            solid = pixels[x, y] >= COLLISION_ALPHA_THRESHOLD
            mask_pixels[x, y] = 255 if solid else 0
            if solid and start is None:
                start = y
            elif not solid and start is not None:
                spans.extend((start, y - 1))
                start = None
        if start is not None:
            spans.extend((start, WORLD_HEIGHT - 1))
        columns.append(spans)

    return mask, columns


def write_typescript_mask(path: Path, columns: list[list[int]]) -> None:
    lines = [
        "// Generated by scripts/build_image_map.py. Do not edit by hand.",
        f"export const DEFAULT_MAP_MASK_WIDTH = {WORLD_WIDTH};",
        f"export const DEFAULT_MAP_MASK_HEIGHT = {WORLD_HEIGHT};",
        "export const DEFAULT_MAP_SOLID_SPANS: readonly (readonly number[])[] = [",
    ]
    lines.extend(f"  [{', '.join(map(str, spans))}]," for spans in columns)
    lines.append("];")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Build a transparent map PNG and shared collision mask.")
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--map-out", required=True, type=Path)
    parser.add_argument("--mask-out", required=True, type=Path)
    parser.add_argument("--ts-out", required=True, type=Path)
    args = parser.parse_args()

    terrain = remove_chroma(Image.open(args.input))
    mask, columns = build_mask(terrain)
    args.map_out.parent.mkdir(parents=True, exist_ok=True)
    args.mask_out.parent.mkdir(parents=True, exist_ok=True)
    args.ts_out.parent.mkdir(parents=True, exist_ok=True)
    terrain.save(args.map_out, optimize=True)
    mask.save(args.mask_out, optimize=True)
    write_typescript_mask(args.ts_out, columns)

    alpha = terrain.getchannel("A")
    visible_pixels = sum(1 for value in alpha.getdata() if value > 0)
    solid_pixels = sum(sum((end - start + 1) for start, end in zip(spans[::2], spans[1::2])) for spans in columns)
    print(f"map={terrain.size}, visible={visible_pixels}, solid={solid_pixels}, columns={len(columns)}")


if __name__ == "__main__":
    main()
